<?php
include "config/base_url.php";
include "config/db.php";
?> 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="<?=$BASE_URL ?>/styles/all.css">
    <title>Document</title>
    
    
</head>
<body>
<?php
    include "views/header.php"
?>
<header id="concept">
 <h3>Beauty is inside you</h3>
 </header>
<section id="itemsss">
   
<div class="item">
</div>

<div class="item">

</div>

<div class="item">

</div>

<div class="item">
</div>

<div class="item">

</div>

</section>
<div id="concept-text">
    <h3>Reflections on beauty</h3>
    <p>Natural beauty comes spontaneously and not by any make over or corrections. It is the way the things are and were right from the day of their creation with no adulteration.

Do we have any measure to evaluate the extent of beauty? Is it objective or subjective? We can easily argue reasonably about whether something is beautiful or not. There is a poplar saying that truth is beauty and beauty is truth, is that correct? Why beauty matter as a subject of concern for all?

One cannot borrow the inner beauty or the outer beauty from any thoughtful or gorgeous person around. It comes to you naturally being a natural gift of God. Outer beauty can be improvised by way of make up but inner beauty is required to be generated by having thoughtful and decent thoughts. Your thought should be fair enough to be a good human being and spread the word of humanity around you.
</p>

</div>
</body>
</html>